### ISSUE TITLE
Cannot set DeepDiff of undefined

### ISSUE THREAD

**Issue by ellej16** [gilbarbara/tree-changes#2]
Hi! 

installed the tours library you made [react-joyride](https://github.com/gilbarbara/react-joyride), and it's pointing at tree-changes/deep-diff error.

<img width="570" alt="screen shot 2018-08-09 at 12 13 47 pm" src="https://user-images.githubusercontent.com/6106749/43877705-f5b4305e-9bcd-11e8-9ae3-7f5fd5332f56.png">

Any idea what the solution is for this one? 

Similar issues arises on deep-diff's v1.0.1: https://github.com/flitbit/diff/issues/131 , https://github.com/flitbit/diff/pull/129 among others

Thanks for react-joyride, btw!

**Comment by xanderberkein** [comment]
Check out my PR! https://github.com/flitbit/diff/pull/134

**Comment by gilbarbara** [comment]
Hello,
Not really... Maybe a webpack configuration?
Does this error happen on development, production or both?

Take a look at this option: https://webpack.js.org/configuration/resolve/#resolve-mainfields

**Comment by ellej16** [comment]
Hi!
This is encountered on development (as it's only on a feature branch currently). 
Will check that option out then, though coming from the issues i posted above it might be coming directly from deep-diff itself. Will confirm later if the option works. 

Thanks a lot!

**Comment by gilbarbara** [comment]
Please try 0.3.3 which has an upgrade deep-diff
