### ISSUE TITLE
Breaking in case of IE

### ISSUE THREAD

**Issue by vikalpgupta-birdeye** [gilbarbara/tree-changes#4]
I am having issue using react-joyride because of this, Its breaking on IE, 
getting this error "Object.getPrototypeOf: 'this' is not an Object", because of the code in src/index.js

`function isPlainObj(...args: any): boolean {
  return args.every(d => {
    if (!d) return false;
    const prototype = Object.getPrototypeOf(d);

    return Object.prototype.toString.call(d)
      .slice(8, -1) === 'Object' && (prototype === null || prototype === Object.getPrototypeOf({}));
  });
}`

**Comment by gilbarbara** [comment]
You'll need a polyfill if you need to support IE

**Comment by vikalpgupta-birdeye** [comment]
Hi @gilbarbara I tried using a polyfill here but it was still not able to handle the error in above code, can you please see if you can include catch this particular error somehow so that it does not break javscript execution.

**Comment by gilbarbara** [comment]
Not really, I'm dropping support for IE in all my packages.

**Comment by vikalpgupta-birdeye** [comment]
@gilbarbara Is there any other way that I can still use joyride on IE having a dependency on this without using a polyfill, as I tried with a polyfill but it was of no use to me. I feel one of the arguments passed is wrong. If it feels right I can also create a PR for the same
